# Generated by Django 2.1.5 on 2019-01-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pubDate',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='visits',
        ),
    ]
